[adwaita_icon_theme]
git-tree-sha1 = "8053afbde1b0990d2a495bc9822545ec73576459"

    [[adwaita_icon_theme.download]]
    sha256 = "2d516ea1db8d07347243a8785202d48a35b486c7578e8e3af0a30db71488903e"
    url = "https://github.com/JuliaBinaryWrappers/adwaita_icon_theme_jll.jl/releases/download/adwaita_icon_theme-v43.0.1+1/adwaita_icon_theme.v43.0.1.any.tar.gz"
