[[adwaita_icon_theme]]
arch = "aarch64"
git-tree-sha1 = "6012e83a109fbe39e539578e2f4275762505f458"
os = "macos"

    [[adwaita_icon_theme.download]]
    sha256 = "2d4f8a418fde95e1613df7339bec0e314f430f1969ffff20cbda6d54bb62ac53"
    url = "https://github.com/JuliaBinaryWrappers/adwaita_icon_theme_jll.jl/releases/download/adwaita_icon_theme-v43.0.1+0/adwaita_icon_theme.v43.0.1.aarch64-apple-darwin.tar.gz"
[[adwaita_icon_theme]]
arch = "aarch64"
git-tree-sha1 = "6012e83a109fbe39e539578e2f4275762505f458"
libc = "glibc"
os = "linux"

    [[adwaita_icon_theme.download]]
    sha256 = "2d4f8a418fde95e1613df7339bec0e314f430f1969ffff20cbda6d54bb62ac53"
    url = "https://github.com/JuliaBinaryWrappers/adwaita_icon_theme_jll.jl/releases/download/adwaita_icon_theme-v43.0.1+0/adwaita_icon_theme.v43.0.1.aarch64-linux-gnu.tar.gz"
[[adwaita_icon_theme]]
arch = "aarch64"
git-tree-sha1 = "6012e83a109fbe39e539578e2f4275762505f458"
libc = "musl"
os = "linux"

    [[adwaita_icon_theme.download]]
    sha256 = "2d4f8a418fde95e1613df7339bec0e314f430f1969ffff20cbda6d54bb62ac53"
    url = "https://github.com/JuliaBinaryWrappers/adwaita_icon_theme_jll.jl/releases/download/adwaita_icon_theme-v43.0.1+0/adwaita_icon_theme.v43.0.1.aarch64-linux-musl.tar.gz"
[[adwaita_icon_theme]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "6012e83a109fbe39e539578e2f4275762505f458"
libc = "glibc"
os = "linux"

    [[adwaita_icon_theme.download]]
    sha256 = "2d4f8a418fde95e1613df7339bec0e314f430f1969ffff20cbda6d54bb62ac53"
    url = "https://github.com/JuliaBinaryWrappers/adwaita_icon_theme_jll.jl/releases/download/adwaita_icon_theme-v43.0.1+0/adwaita_icon_theme.v43.0.1.armv6l-linux-gnueabihf.tar.gz"
[[adwaita_icon_theme]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "6012e83a109fbe39e539578e2f4275762505f458"
libc = "musl"
os = "linux"

    [[adwaita_icon_theme.download]]
    sha256 = "2d4f8a418fde95e1613df7339bec0e314f430f1969ffff20cbda6d54bb62ac53"
    url = "https://github.com/JuliaBinaryWrappers/adwaita_icon_theme_jll.jl/releases/download/adwaita_icon_theme-v43.0.1+0/adwaita_icon_theme.v43.0.1.armv6l-linux-musleabihf.tar.gz"
[[adwaita_icon_theme]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "6012e83a109fbe39e539578e2f4275762505f458"
libc = "glibc"
os = "linux"

    [[adwaita_icon_theme.download]]
    sha256 = "2d4f8a418fde95e1613df7339bec0e314f430f1969ffff20cbda6d54bb62ac53"
    url = "https://github.com/JuliaBinaryWrappers/adwaita_icon_theme_jll.jl/releases/download/adwaita_icon_theme-v43.0.1+0/adwaita_icon_theme.v43.0.1.armv7l-linux-gnueabihf.tar.gz"
[[adwaita_icon_theme]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "6012e83a109fbe39e539578e2f4275762505f458"
libc = "musl"
os = "linux"

    [[adwaita_icon_theme.download]]
    sha256 = "2d4f8a418fde95e1613df7339bec0e314f430f1969ffff20cbda6d54bb62ac53"
    url = "https://github.com/JuliaBinaryWrappers/adwaita_icon_theme_jll.jl/releases/download/adwaita_icon_theme-v43.0.1+0/adwaita_icon_theme.v43.0.1.armv7l-linux-musleabihf.tar.gz"
[[adwaita_icon_theme]]
arch = "i686"
git-tree-sha1 = "6012e83a109fbe39e539578e2f4275762505f458"
libc = "glibc"
os = "linux"

    [[adwaita_icon_theme.download]]
    sha256 = "2d4f8a418fde95e1613df7339bec0e314f430f1969ffff20cbda6d54bb62ac53"
    url = "https://github.com/JuliaBinaryWrappers/adwaita_icon_theme_jll.jl/releases/download/adwaita_icon_theme-v43.0.1+0/adwaita_icon_theme.v43.0.1.i686-linux-gnu.tar.gz"
[[adwaita_icon_theme]]
arch = "i686"
git-tree-sha1 = "6012e83a109fbe39e539578e2f4275762505f458"
libc = "musl"
os = "linux"

    [[adwaita_icon_theme.download]]
    sha256 = "2d4f8a418fde95e1613df7339bec0e314f430f1969ffff20cbda6d54bb62ac53"
    url = "https://github.com/JuliaBinaryWrappers/adwaita_icon_theme_jll.jl/releases/download/adwaita_icon_theme-v43.0.1+0/adwaita_icon_theme.v43.0.1.i686-linux-musl.tar.gz"
[[adwaita_icon_theme]]
arch = "i686"
git-tree-sha1 = "83610426d0bfee961ce822688b90b01377a3dfe6"
os = "windows"

    [[adwaita_icon_theme.download]]
    sha256 = "6394d8a92e3b1bb1ad28d780ef42a0e5adc8e35f46f8bd7c8d15780a10abf484"
    url = "https://github.com/JuliaBinaryWrappers/adwaita_icon_theme_jll.jl/releases/download/adwaita_icon_theme-v43.0.1+0/adwaita_icon_theme.v43.0.1.i686-w64-mingw32.tar.gz"
[[adwaita_icon_theme]]
arch = "powerpc64le"
git-tree-sha1 = "6012e83a109fbe39e539578e2f4275762505f458"
libc = "glibc"
os = "linux"

    [[adwaita_icon_theme.download]]
    sha256 = "2d4f8a418fde95e1613df7339bec0e314f430f1969ffff20cbda6d54bb62ac53"
    url = "https://github.com/JuliaBinaryWrappers/adwaita_icon_theme_jll.jl/releases/download/adwaita_icon_theme-v43.0.1+0/adwaita_icon_theme.v43.0.1.powerpc64le-linux-gnu.tar.gz"
[[adwaita_icon_theme]]
arch = "x86_64"
git-tree-sha1 = "6012e83a109fbe39e539578e2f4275762505f458"
os = "macos"

    [[adwaita_icon_theme.download]]
    sha256 = "2d4f8a418fde95e1613df7339bec0e314f430f1969ffff20cbda6d54bb62ac53"
    url = "https://github.com/JuliaBinaryWrappers/adwaita_icon_theme_jll.jl/releases/download/adwaita_icon_theme-v43.0.1+0/adwaita_icon_theme.v43.0.1.x86_64-apple-darwin.tar.gz"
[[adwaita_icon_theme]]
arch = "x86_64"
git-tree-sha1 = "6012e83a109fbe39e539578e2f4275762505f458"
libc = "glibc"
os = "linux"

    [[adwaita_icon_theme.download]]
    sha256 = "2d4f8a418fde95e1613df7339bec0e314f430f1969ffff20cbda6d54bb62ac53"
    url = "https://github.com/JuliaBinaryWrappers/adwaita_icon_theme_jll.jl/releases/download/adwaita_icon_theme-v43.0.1+0/adwaita_icon_theme.v43.0.1.x86_64-linux-gnu.tar.gz"
[[adwaita_icon_theme]]
arch = "x86_64"
git-tree-sha1 = "6012e83a109fbe39e539578e2f4275762505f458"
libc = "musl"
os = "linux"

    [[adwaita_icon_theme.download]]
    sha256 = "2d4f8a418fde95e1613df7339bec0e314f430f1969ffff20cbda6d54bb62ac53"
    url = "https://github.com/JuliaBinaryWrappers/adwaita_icon_theme_jll.jl/releases/download/adwaita_icon_theme-v43.0.1+0/adwaita_icon_theme.v43.0.1.x86_64-linux-musl.tar.gz"
[[adwaita_icon_theme]]
arch = "x86_64"
git-tree-sha1 = "6012e83a109fbe39e539578e2f4275762505f458"
os = "freebsd"

    [[adwaita_icon_theme.download]]
    sha256 = "2d4f8a418fde95e1613df7339bec0e314f430f1969ffff20cbda6d54bb62ac53"
    url = "https://github.com/JuliaBinaryWrappers/adwaita_icon_theme_jll.jl/releases/download/adwaita_icon_theme-v43.0.1+0/adwaita_icon_theme.v43.0.1.x86_64-unknown-freebsd.tar.gz"
[[adwaita_icon_theme]]
arch = "x86_64"
git-tree-sha1 = "83610426d0bfee961ce822688b90b01377a3dfe6"
os = "windows"

    [[adwaita_icon_theme.download]]
    sha256 = "6394d8a92e3b1bb1ad28d780ef42a0e5adc8e35f46f8bd7c8d15780a10abf484"
    url = "https://github.com/JuliaBinaryWrappers/adwaita_icon_theme_jll.jl/releases/download/adwaita_icon_theme-v43.0.1+0/adwaita_icon_theme.v43.0.1.x86_64-w64-mingw32.tar.gz"
