[[adwaita_icon_theme]]
arch = "x86_64"
git-tree-sha1 = "17b6682b222ef6ff06805a6c674b00c68ddc8a9c"
os = "macos"

    [[adwaita_icon_theme.download]]
    sha256 = "ee99b1229606958f084296b1eb18db1c33d215ab398e462d2274e267a12331ee"
    url = "https://github.com/JuliaBinaryWrappers/adwaita_icon_theme_jll.jl/releases/download/adwaita_icon_theme-v3.33.92+3/adwaita_icon_theme.v3.33.92.x86_64-apple-darwin14.tar.gz"
[[adwaita_icon_theme]]
arch = "i686"
git-tree-sha1 = "0a352dded55893242d516963990278f9e386eeef"
libc = "glibc"
os = "linux"

    [[adwaita_icon_theme.download]]
    sha256 = "5dc7cdafb6ca3491ca15c00a3472381c32e058bfbeb15b917912f424862f42ba"
    url = "https://github.com/JuliaBinaryWrappers/adwaita_icon_theme_jll.jl/releases/download/adwaita_icon_theme-v3.33.92+3/adwaita_icon_theme.v3.33.92.i686-linux-gnu.tar.gz"
[[adwaita_icon_theme]]
arch = "x86_64"
git-tree-sha1 = "72c8e5fda934b8d41347291e3a7de4f953d83c78"
os = "freebsd"

    [[adwaita_icon_theme.download]]
    sha256 = "a606cce0f21ac221ecff45b47aa852c213b4b2cfd56b5fc03713c25944ba2a77"
    url = "https://github.com/JuliaBinaryWrappers/adwaita_icon_theme_jll.jl/releases/download/adwaita_icon_theme-v3.33.92+3/adwaita_icon_theme.v3.33.92.x86_64-unknown-freebsd11.1.tar.gz"
[[adwaita_icon_theme]]
arch = "powerpc64le"
git-tree-sha1 = "e7386dd51ffe466f7bf0431fcef01906e848d7e5"
libc = "glibc"
os = "linux"

    [[adwaita_icon_theme.download]]
    sha256 = "942997c9117b3f9a266ca6eda1a4e76f191ac7588da0f6954bd5aff570a8b85b"
    url = "https://github.com/JuliaBinaryWrappers/adwaita_icon_theme_jll.jl/releases/download/adwaita_icon_theme-v3.33.92+3/adwaita_icon_theme.v3.33.92.powerpc64le-linux-gnu.tar.gz"
[[adwaita_icon_theme]]
arch = "x86_64"
git-tree-sha1 = "accb491ea025aabbf0567aa5bb15e739e92a359d"
libc = "musl"
os = "linux"

    [[adwaita_icon_theme.download]]
    sha256 = "e56b99b3ef9adf523a1086bfb4276966cd8add1102e7d700644bb7e9629f026e"
    url = "https://github.com/JuliaBinaryWrappers/adwaita_icon_theme_jll.jl/releases/download/adwaita_icon_theme-v3.33.92+3/adwaita_icon_theme.v3.33.92.x86_64-linux-musl.tar.gz"
[[adwaita_icon_theme]]
arch = "x86_64"
git-tree-sha1 = "18bf89fa7a831cbb8d5a1785406bd24e4a3d887b"
libc = "glibc"
os = "linux"

    [[adwaita_icon_theme.download]]
    sha256 = "26e591c1a10e712f83582cfb45ce4d809f3ea8848ac4e990cf998e091ea91b37"
    url = "https://github.com/JuliaBinaryWrappers/adwaita_icon_theme_jll.jl/releases/download/adwaita_icon_theme-v3.33.92+3/adwaita_icon_theme.v3.33.92.x86_64-linux-gnu.tar.gz"
[[adwaita_icon_theme]]
arch = "x86_64"
git-tree-sha1 = "a940c3d6be54ec6a074c99180694bc9d01b638bd"
os = "windows"

    [[adwaita_icon_theme.download]]
    sha256 = "4549607a9ea11d113c1d49a323ab5e0dff8e0b07fd6089aca4bb4301123160d3"
    url = "https://github.com/JuliaBinaryWrappers/adwaita_icon_theme_jll.jl/releases/download/adwaita_icon_theme-v3.33.92+3/adwaita_icon_theme.v3.33.92.x86_64-w64-mingw32.tar.gz"
[[adwaita_icon_theme]]
arch = "aarch64"
git-tree-sha1 = "9dd32a201a1c35c53bbed2021ade71c6f875394e"
libc = "musl"
os = "linux"

    [[adwaita_icon_theme.download]]
    sha256 = "749d2d71ac8827475a0d77ecb5eea89b4e37f6d05b61a2b6c3fc4178e9527e8e"
    url = "https://github.com/JuliaBinaryWrappers/adwaita_icon_theme_jll.jl/releases/download/adwaita_icon_theme-v3.33.92+3/adwaita_icon_theme.v3.33.92.aarch64-linux-musl.tar.gz"
[[adwaita_icon_theme]]
arch = "armv7l"
git-tree-sha1 = "2da7edea60653a87c7c15dac0518b747afc3b2d2"
libc = "glibc"
os = "linux"

    [[adwaita_icon_theme.download]]
    sha256 = "738eea750656959413d512c9cd92dc447b05e0d62c60f364ac01c495ec86e97a"
    url = "https://github.com/JuliaBinaryWrappers/adwaita_icon_theme_jll.jl/releases/download/adwaita_icon_theme-v3.33.92+3/adwaita_icon_theme.v3.33.92.arm-linux-gnueabihf.tar.gz"
[[adwaita_icon_theme]]
arch = "i686"
git-tree-sha1 = "fa8e650bbdb01af363cc57287cdc9b8099cd6206"
libc = "musl"
os = "linux"

    [[adwaita_icon_theme.download]]
    sha256 = "48d30d09fc8aa3a8286df6c65146884e65468274b5d3045716d8d2321b5b4fd6"
    url = "https://github.com/JuliaBinaryWrappers/adwaita_icon_theme_jll.jl/releases/download/adwaita_icon_theme-v3.33.92+3/adwaita_icon_theme.v3.33.92.i686-linux-musl.tar.gz"
[[adwaita_icon_theme]]
arch = "armv7l"
git-tree-sha1 = "f2f1b9c529c237f9c7f87e26657cded5d3281246"
libc = "musl"
os = "linux"

    [[adwaita_icon_theme.download]]
    sha256 = "95c44fe152b05d4b9544b2389dd13a5c336d357a3a1f2ab9ef52aa67d626a7ac"
    url = "https://github.com/JuliaBinaryWrappers/adwaita_icon_theme_jll.jl/releases/download/adwaita_icon_theme-v3.33.92+3/adwaita_icon_theme.v3.33.92.arm-linux-musleabihf.tar.gz"
[[adwaita_icon_theme]]
arch = "aarch64"
git-tree-sha1 = "38c15a169f763b7456b49acacbdc6471187db737"
libc = "glibc"
os = "linux"

    [[adwaita_icon_theme.download]]
    sha256 = "eb43149251998e6e2ba163a82eab3f31b789459355f938364fda5135b8f53b15"
    url = "https://github.com/JuliaBinaryWrappers/adwaita_icon_theme_jll.jl/releases/download/adwaita_icon_theme-v3.33.92+3/adwaita_icon_theme.v3.33.92.aarch64-linux-gnu.tar.gz"
[[adwaita_icon_theme]]
arch = "i686"
git-tree-sha1 = "411f303f6be5e3c9399d5dc60dd51d82a4d0801d"
os = "windows"

    [[adwaita_icon_theme.download]]
    sha256 = "aac05c0eec9d2f32d217caeb3260df0cffbd45d55ee1b431d7658408d3a13dc8"
    url = "https://github.com/JuliaBinaryWrappers/adwaita_icon_theme_jll.jl/releases/download/adwaita_icon_theme-v3.33.92+3/adwaita_icon_theme.v3.33.92.i686-w64-mingw32.tar.gz"
