[adwaita_icon_theme]
git-tree-sha1 = "6012e83a109fbe39e539578e2f4275762505f458"

    [[adwaita_icon_theme.download]]
    sha256 = "2d4f8a418fde95e1613df7339bec0e314f430f1969ffff20cbda6d54bb62ac53"
    url = "https://github.com/JuliaBinaryWrappers/adwaita_icon_theme_jll.jl/releases/download/adwaita_icon_theme-v43.0.0+0/adwaita_icon_theme.v43.0.0.any.tar.gz"
